curl;jq instead of curl|jq
Debugging
```
jq: error: syntax error, unexpected INVALID_CHARACTER (Windows cmd shell quoting issues?) at <top-level>, line 1:
.assets[] | select(.content_type == \"application/x-zip-compressed\") | .browser_download_url                                    
jq: 1 compile error
ResourceUnavailable: D:\a\_temp\b6038505-26ff-4313-a95a-0ffbeed13b7e.ps1:3
Line |
   3 |    curl -H "Accept: application/vnd.github.v3+json" -s "https://api.gi …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'curl.exe' failed to run: The pipe is being closed.At
     | D:\a\_temp\b6038505-26ff-4313-a95a-0ffbeed13b7e.ps1:3 char:3 +   curl -H "Accept:
     | application/vnd.github.v3+json" -s "https://api.gi … +  
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
Error: Process completed with exit code 1.
```